language: node_js
node_js:
  - "6"

notifications:
  email: false

cache:
  directories:
    - node_modules

install:
  - npm install
  - cd client/ && npm install
script:
  - cd ../ && npm run build
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  skip_cleanup: true
  app: ewapp
