export const sagaWaterActions = {
    WATER_EDITOR_ADD: 'WATER_EDITOR_ADD',
    DELETE_WATER_ITEM: 'DELETE_WATER_ITEM',
    EDIT_WATER_ITEM:  'EDIT_WATER_ITEM',
    LOAD_WATER_LIST: 'LOAD_WATER_LIST'
}